Build and push Docker image into docker.io/absaoss
AbsaOSS/samlet pull request #1
Opened 2020-11-12 13:08 UTC by k0da

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2020-11-13 16:03 UTC, kuritka requested changes

2020-11-13 16:03 UTC, kuritka commented on Dockerfile
> +FROM golang:1.14 as builder
Q: did you consider 1.15 ? https://github.com/AbsaOSS/samlet/blob/main/go.mod#L3

2020-11-16 11:29 UTC, k0da commented
@kuritka done

2020-11-16 12:28 UTC, kuritka approved these changes

2020-11-16 12:38 UTC, ytsarev approved these changes

2020-11-16 12:46 UTC, merged