Add helm chart
AbsaOSS/samlet pull request #2
Opened 2020-11-12 13:58 UTC by k0da

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

2020-11-15 22:24 UTC, ytsarev requested changes
Shouldn't we put chart into /charts directory which kind of a common practice?

2020-11-15 22:25 UTC, ytsarev requested changes

2020-11-15 22:25 UTC, ytsarev commented on config/helm/samlet/Chart.yaml
> +appVersion: 1.16.0
Please consider syncing version and appVersion as we are doing in k8gb

2020-11-16 10:01 UTC, k0da commented
@ytsarev kubebuiler stores everything into /config, it would be logical to put chart there too. If you're strongly against. I have no problem changing it

2020-11-16 11:25 UTC, ytsarev commented
@k0da no strong opinion that, let's keep it under `/config`

2020-11-16 11:25 UTC, ytsarev approved these changes

2020-11-16 11:28 UTC, merged